Database update
DrewKestell/BloogBot pull request #11
Opened 2023-06-18 21:50 UTC by Eric5766

- Added ability to configure database type (currently sqlite or mssql) 
- IRepository interface for all methods adding or retrieving data.
- SqlRepository abstract class for SQL specific methods
- TSqlRepository & SqliteRepository - Both implementing IRepository & SqlRepository.  Each creates/repairs its respective database automatically (Sql schemas included) & handles syntax specific to that database type.

- Also added setting to turn off Discord bot functionality

2023-06-25 02:21 UTC, DrewKestell requested changes
Good job :)

Take a look at the comment I made about dependencies and ping me once it's ready to merge.

2023-06-25 02:21 UTC, DrewKestell commented on BloogBot/packages.config
> +  <package id="EntityFramework" version="6.4.4" targetFramework="net461" />
Can you double check all of these dependencies are required? EntityFramework for example is a pretty heavy dependency, and I don't think you're actually using it.

2023-07-05 17:03 UTC, Eric5766 commented
> Good job :)
> 
> Take a look at the comment I made about dependencies and ping me once it's ready to merge.

Sorry for the delay - Have stripped the most of them out and seems to work fine for me still!

2023-07-06 14:12 UTC, DrewKestell approved these changes

2023-07-06 14:15 UTC, merged